#!/bin/bash

function bi() {
  pkg="$1"
  if ! brew list -1 | grep -q "^${pkg}\$"; then
    brew install "$@"
  fi
}

function bci() {
  pkg="$1"
  if ! brew cask list -1 | grep -q "^${pkg}\$"; then
    brew cask install "$@"
  fi
}

sudo -v

# Update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade --all

# Install GNU core utilities (those that come with OS X are outdated)
bi coreutils

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
bi findutils

# Install GNU `sed`, overwriting the built-in `sed`
# bi gnu-sed --with-default-names

# Install `bash`
bi bash
brew tap homebrew/versions
bi bash-completion2

# Install `wget` with IRI support
bi wget --with-iri

# Install more recent versions of some OS X tools
# bi homebrew/dupes/grep
# bi homebrew/dupes/openssh

# Install git
bi git

# Install vcprompt
bi vcprompt

# Install grc
bi grc

# Install python
bi python
bi python3

# Install fzf
bi fzf

# Install fasd
bi fasd

# Install httpie
bi httpie

# Install 7-zip
bi p7zip

# Install unrar
bi unrar

# Install vim
bi vim

# Install tmux
bi tmux
brew pin tmux
bi reattach-to-user-namespace

# Install Midnight Commander
bi midnight-commander

# Install google-chrome
bci google-chrome
bci chromium

# Install firefox
bci firefox

# Install caffeine
bci caffeine

# Install cheatsheet
bci cheatsheet

# Install appcleaner
bci appcleaner

# Install skype
bci skype

# Install the_silver_searcher
bi the_silver_searcher

# Install transmission
bci transmission

# Install ssh-copy-id
bi ssh-copy-id

# Terminal
bci iterm2

# Seil
bci seil
/Applications/Seil.app/Contents/Library/bin/seil set keycode_capslock 80

# Dropbox
bci dropbox

# Google drive
bci google-drive

# Remove outdated versions from the cellar
brew cleanup

unset -f bci
unset -f bi
