#!/bin/bash

# Show date in toolbar
gsettings set com.canonical.indicator.datetime show-date true

# Only show battery icon when it's used
gsettings set com.canonical.indicator.power icon-policy "charge"

# Show battery percentage
gsettings set com.canonical.indicator.power show-percentage true

# Show battery time left
gsettings set com.canonical.indicator.power show-time true

# Use list view by default
gsettings set org.gnome.nautilus.preferences default-folder-viewer "list-view"

# Sort files by type
gsettings set org.gnome.nautilus.preferences default-sort-order "type"

# List directories first
gsettings set org.gnome.nautilus.preferences sort-directories-first true

# Never show image thumbnails
# gsettings set org.gnome.nautilus.preferences show-image-thumbnails "never"

# Use tree-view
gsettings set org.gnome.nautilus.list-view use-tree-view true

# Small zoom level
gsettings set org.gnome.nautilus.list-view default-zoom-level "small"

# Set keyboard languages
gsettings set org.gnome.libgnomekbd.keyboard layouts "['uk', 'us']"

# Show hidden files
gsettings set org.gtk.Settings.FileChooser show-hidden true

# Allow setting volume above 100%
gsettings set com.ubuntu.sound allow-amplified-volume true
